INCLUDE(FindPackageHandleStandardArgs)

FIND_PATH(ARAVIS_INCLUDE_PATH arv.h
  "$ENV{ARAVIS_INCLUDE_PATH}"
  /opt/aravis/include
)

FIND_LIBRARY(ARAVIS_LIBRARY aravis-0.4
  "$ENV{ARAVIS_LIBRARY}"
  /opt/aravis/lib/
)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(ARAVIS DEFAULT_MSG
  ARAVIS_INCLUDE_PATH
  ARAVIS_LIBRARY)

